### ISSUE TITLE
The 'Total value' label is not getting updated

### ISSUE THREAD

**Issue by Richard809** [KyberNetwork/KyberSwap#395]
![untitled](https://user-images.githubusercontent.com/8468305/35654684-756c866a-06c4-11e8-8616-73a7e8bc133e.png)

Problem: 

When the action GLOBAL.UPDATE_RATE_USD_FULFILLED is being resolved by the 'tokensReducer.js', one (or more) of tokens's rateUSD property are not updated properly. I'm pasting the code for reference: 

```javascript 
var tokens = { ...state.tokens }
var rates = action.payload.rates
//map token
var mapToken = {}
rates.map(rate => {
  mapToken[rate.symbol] = rate.price_usd
})

//push data
var newTokens = {}
Object.keys(tokens).map(key => {
  var token = tokens[key]
  token.rateUSD = mapToken[token.symbol]
  newTokens[key] = token
})
return Object.assign({}, state, { tokens: newTokens })
```
The 'rates' variable does not always contains all of the tokens in the variable 'tokens', meaning rateUSD will be undefined if the properties (where the property name or token symbol 'key => {' is used as reference) don't match.

Now in AccountBalanceView when the function getBalanceUsd() is called, a sum by all the tokens is made but since there's undefined rateUSD properties, the multiplication will result in a NaN and converts.roundingNumber() returning 0 as consequence.

Fix: 

I will not provide a direct fix based on the following concerns: 

* The env file kovan.json has SALT listed, which is one the tokens not returned by the back-end. Since I don't know how the back-end and deployments are handle I can't comment on that.
* The code assumes that there will always be a 1 to 1 existence for the tokens in the account balance and whatever is returned by the back-end.
* Validation can fix the issue (again that could be a deployment responsibility).

**Comment by tranvictor** [comment]
Thank you @Richard809 for the very informative bug report ever. We will take a look as soon as possible.

**Comment by Richard809** [comment]
@tranvictor god is in the details...

**Comment by andrewsource147** [comment]
It've been fixed in previous release, Please check our new website:  https://kyberswap.com/swap/eth-knc
