### ISSUE TITLE
Request: Exchange | Transfer buttons

### ISSUE THREAD

**Issue by lewisabela** [KyberNetwork/KyberSwap#486]
Can we turn these two links into clickable buttons that become highlighted when hovering over and a button press change? I didn't even noticed this section existed. 
Another few requests:
- Change "Address" to "Receiving Address" 
- Change the "Token/Amount" to "Token & Amount To Send"
- Make the text in the textbox of the receiving address centered and larger. 
- Change "Total value" to "Total Wallet Value"

**Comment by andrewsource147** [comment]
Ok, designer is finding solutions
