### ISSUE TITLE
Send Offline

### ISSUE THREAD

**Issue by gernotpokorny** [KyberNetwork/KyberSwap#493]
How can people use KyberNetwork with Offline transactions? Offline transaction means signing a tx on an offline computer. 

For me and I guess many other people entering a private key on an online pc is no option at all. Using a ledger is no option too for many people since it is not trustless due to that the firmware is not open source. Many people are in crypto because of the trustless nature.

**Comment by andrewsource147** [comment]
Thanks you very much, We will update document soon, will guide user how to sign transaction and send transaction to network.

**Comment by andrewsource147** [comment]
Contact our developer group (telegram) for further information: https://t.me/KyberDeveloper
