### ISSUE TITLE
Issues on Firefox browser

### ISSUE THREAD

**Issue by Gamvu** [KyberNetwork/KyberSwap#494]
1. Copy transaction hash action
- It is unable to make copy transaction hash action when clicking the button for copy command.
- Config: Win 10 - 64 bit, Firefox browser.
- Wallet: MetaMask, Private key, Json 
![copy transaction hash action](https://user-images.githubusercontent.com/36144425/36883293-b98dbf7c-1e0b-11e8-9d90-138349b722a2.png)

**Comment by Gamvu** [comment]
2. MetaMask confirm transaction panel doesn't show up well.
 - After clicking confirm button in Exchange confirm panel, MetaMask confirm transaction panel shows up just some seconds then disappears. 
- Config: Win 10 - 64 bit, Firefox browser.
- Wallet: MetaMask.

**Comment by tuyenkhuc** [comment]
this issue still happen on FireFox (Windows 10)
