### ISSUE TITLE
UI Recommendation from users - Rate Display

### ISSUE THREAD

**Issue by imweihuang** [KyberNetwork/KyberSwap#572]
Below are two UI recommendations collected from users for your consideration:

1. An user recommended the rate of DAI should be displayed as ETH/DAI instead of DAI/ETH, as for the people who usually trade ETH with DAI, they usually look at ETH price in USD or DAI. Also, some users would appreciate seeing ETH price while using our wallet.
<img width="476" alt="screen shot 2018-04-20 at 7 42 24 pm" src="https://user-images.githubusercontent.com/24487707/39049183-fb3a33ea-44d2-11e8-99ff-4eac5fc70b53.png">

> My thought: only making DAI rate to ETH/DAI makes rates look inconsistent, would it be good to have a dedicated place to display ETH/Stablecoin rate?

2. Another user recommended another way, which is to display two rate formats for each coin, like displaying both KNC/ETH and ETH/KNC. 

> My thought: doing this may be challenging to keep the page simple and clean?

**Comment by andrewsource147** [comment]
Thank for your comment, we'll consider in the next releases
