### ISSUE TITLE
The partner instant exchange SimpleSwap.io

### ISSUE THREAD

**Issue by SimpleSwap** [KyberNetwork/KyberSwap#895]
Hi,

I am Nicolas, the manager at SimpleSwap.io, an instant cryptocurrency exchange.

We present a simple and easy-to-use platform that works without registration and limits and allows users to make swaps in just two clicks.

We successfully support KNC on our service for a long time and we have been exchanging KNC for more than 200 coins to our customers. I tried to find contact with your team but without results.

I'm sorry that I invaded here, but maybe you can tell me where I can turn. I would like to make contact so we can have an interaction.

**Comment by andrewsource147** [comment]
Hi Nicolas, 

I'm sorry for the late reply. We currently have internal system to monitor status of KyberSwap, so we don't check issues in github on a regular basic. You can join your telegram groups and show your case, our team will make contact with you.
